# Cloudflare Pages + Functions for chadunderwood.com
name = "chadunderwood"
compatibility_date = "2025-09-01"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "SIGNAL_POSTS"
id = "0fe1c887237143549c234519560962b9"

[[kv_namespaces]]
binding = "WRITING_POSTS"
id = "9cb22f32c1464b3db4e599f00bb24620"
